--- 
- hosts: all
  gather_facts: true 
  tasks: 
    - name: Print the variables
      debug: 
        msg: "{{ ansible_distribution }}  {{ ansible_distribution_version }} {{ ansible_memfree_mb }} {{ ansible_memtotal_mb }} {{ ansible_processor_cores }} {{ ansible_architecture }}"
