---
- hosts: all
  gather_facts: false
  vars:
    command: "ssh -V"
  tasks:
    - name: Check SSH version
      shell: "{{ command }}"
      register: ssh_version
    - name: Print ssh version
      debug:
        #msg: "SSH version of {{ inventory_hostname }} is {{ ssh_version }} "
        var: ssh_version 