---
- hosts: all
  gather_facts: true
  tasks:
    - name: Show inventory hostname variables
      debug:
        #msg: "Hello world!" # not required. The customized message that is printed. If omitted, prints a generic message.
        var: inventory_hostname # not required. A variable name to debug. Mutually exclusive with the C(msg) option. Be aware that this option already runs in Jinja2 context and has an implicit C({{ }}) wrapping, so you should not be using Jinja2 delimiters unless you are looking for double interpolation.
        verbosity: 0 # not required. A number that controls when the debug is run, if you set to 3 it will only run debug when -vvv or above
      